name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Erster Job: Kompilieren
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Install Workload
        run: dotnet workload restore
      - name: Build
        run: dotnet build --configuration Release
      
      # Optional: Hier müsstest du die Artefakte (DLLs) "hochladen", 
      # damit der Test-Job sie nutzen kann. 
      # Einfacher für den Anfang: Im Test-Job nochmal kurz builden.

  # Zweiter Job: Testen
  test:
    needs: build # Dieser Job wartet auf den 'build' Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Install Workload
        run: dotnet workload restore
      - name: Run Tests
        run: dotnet test **/*Tests.csproj --configuration Release
